// Generated by CoffeeScript 1.4.0
var create;

create = {
  q_template: JST["question"],
  init: function() {
    this.detect_elements();
    return this.bind_events();
  },
  detect_elements: function() {
    this.new_q = $("#new-question");
    return this.form = $("form");
  },
  bind_events: function() {
    this.init_redactor();
    this.new_click();
    return this.form_validation();
  },
  new_click: function() {
    var _this = this;
    return this.new_q.click(function(e) {
      var el, questions;
      el = $(e.currentTarget);
      _this.form.validationEngine('detach');
      questions = $('.question');
      questions.last().after(_this.q_template({
        number: questions.size() + 1
      }));
      _this.init_redactor();
      return _this.form_validation();
    });
  },
  remove_question: function(element) {
    return $(element).parents('.question').remove();
  },
  init_redactor: function() {
    return $('.textarea').last().wysihtml5();
  },
  form_validation: function() {
    return this.form.validationEngine('attach');
  }
};

$(document).ready(function() {
  return create.init();
});
